import { useState, useMemo } from 'react'
import type { Brand, Prompt, Attribute, PromptType } from '../types'

interface OnboardingProps {
  onComplete: (data: { ownBrand: Brand; competitors: Brand[]; prompts: Prompt[]; attributes: Attribute[]; runScan: boolean }) => void
}

const SWATCHES = ['#FF5C35', '#00A1E0', '#1A1A2E', '#E42527', '#1A3C5E', '#6C3EF4', '#10B981', '#F59E0B']

type PromptDraft = { text: string; type: PromptType }

const TYPE_META: Record<PromptType, { label: string; rank: number; blurb: string; example: string }> = {
  category: {
    label: 'Category',
    rank: 1,
    blurb: 'Closest to real buyer behaviour — no brand named.',
    example: 'best {category} for {segment}',
  },
  competitor_anchored: {
    label: 'Competitor-anchored',
    rank: 2,
    blurb: 'Real query, but anchored to a competitor.',
    example: 'alternatives to {competitor}',
  },
  association_probe: {
    label: 'Brand',
    rank: 3,
    blurb: 'Diagnostic — useful for validation, not buyer-journey signal.',
    example: 'what is {brand} known for',
  },
}

const SUGGESTED_ATTRIBUTES = [
  'Ease of use', 'Innovation', 'Reliability', 'Value for money',
  'Enterprise ready', 'Customisation', 'Integration depth', 'Automation',
  'Customer support', 'Security', 'Speed', 'Design quality',
]

export function Onboarding({ onComplete }: OnboardingProps) {
  const [step, setStep] = useState(0)

  // Step 0 — Brand
  const [brandName, setBrandName] = useState('')
  const [brandColor, setBrandColor] = useState(SWATCHES[0])

  // Step 1 — Competitors
  const [competitors, setCompetitors] = useState<{ name: string; color: string }[]>([])
  const [compName, setCompName] = useState('')
  const [compColor, setCompColor] = useState(SWATCHES[1])

  // Step 2 — Attributes
  const [selectedAttrs, setSelectedAttrs] = useState<string[]>([])
  const [customAttr, setCustomAttr] = useState('')

  // Step 3 — Prompts
  const [category, setCategory] = useState('')
  const [segment, setSegment] = useState('')
  const [enabledTypes, setEnabledTypes] = useState<Record<PromptType, boolean>>({
    category: true,
    competitor_anchored: true,
    association_probe: false,
  })
  const [generatedPrompts, setGeneratedPrompts] = useState<PromptDraft[]>([])
  const [editingPrompts, setEditingPrompts] = useState(false)
  const [showAdvanced, setShowAdvanced] = useState(false)
  const [customPrompt, setCustomPrompt] = useState('')
  const [customType, setCustomType] = useState<PromptType>('category')
  const [customPrompts, setCustomPrompts] = useState<PromptDraft[]>([])

  // Step 4 — Final
  const [selectedModel, setSelectedModel] = useState('All')

  const brandLabel = brandName.trim() || 'your brand'
  const categoryLabel = category.trim() || 'CRM'
  const segmentLabel = segment.trim() || 'SMEs'

  const autoGenerated = useMemo<PromptDraft[]>(() => {
    const out: PromptDraft[] = []
    if (enabledTypes.category) {
      out.push({ type: 'category', text: `best ${categoryLabel} for ${segmentLabel}` })
      out.push({ type: 'category', text: `top ${categoryLabel} platforms in 2025` })
      out.push({ type: 'category', text: `which ${categoryLabel} should I choose for ${segmentLabel}` })
    }
    if (enabledTypes.competitor_anchored) {
      const comps = competitors.length > 0 ? competitors.map(c => c.name) : ['the market leader']
      comps.slice(0, 3).forEach(c => {
        out.push({ type: 'competitor_anchored', text: `alternatives to ${c}` })
      })
      if (comps.length >= 1) {
        out.push({ type: 'competitor_anchored', text: `${brandLabel} vs ${comps[0]} — which is better` })
      }
    }
    if (enabledTypes.association_probe) {
      out.push({ type: 'association_probe', text: `what is ${brandLabel} known for` })
      out.push({ type: 'association_probe', text: `describe ${brandLabel}'s strengths as a ${categoryLabel}` })
    }
    return out
  }, [enabledTypes, categoryLabel, segmentLabel, brandLabel, competitors])

  // Use edited list if user has touched it, otherwise track auto
  const effectiveGenerated = editingPrompts ? generatedPrompts : autoGenerated
  const allPrompts: PromptDraft[] = [...effectiveGenerated, ...customPrompts]


  const handleAddComp = () => {
    if (!compName.trim() || competitors.length >= 4) return
    setCompetitors(prev => [...prev, { name: compName.trim(), color: compColor }])
    setCompName('')
    const usedColors = [...competitors.map(c => c.color), brandColor, compColor]
    const next = SWATCHES.find(s => !usedColors.includes(s)) ?? SWATCHES[2]
    setCompColor(next)
  }

  const toggleAttr = (name: string) => {
    setSelectedAttrs(prev =>
      prev.includes(name) ? prev.filter(a => a !== name) : [...prev, name]
    )
  }

  const handleAddCustomAttr = () => {
    if (!customAttr.trim() || selectedAttrs.includes(customAttr.trim())) return
    setSelectedAttrs(prev => [...prev, customAttr.trim()])
    setCustomAttr('')
  }

  const startEditing = () => {
    if (!editingPrompts) {
      setGeneratedPrompts(autoGenerated)
      setEditingPrompts(true)
    }
  }

  const removeGenerated = (idx: number) => {
    startEditing()
    setGeneratedPrompts(prev => {
      const base = editingPrompts ? prev : autoGenerated
      return base.filter((_, i) => i !== idx)
    })
  }

  const updateGenerated = (idx: number, text: string) => {
    startEditing()
    setGeneratedPrompts(prev => {
      const base = editingPrompts ? prev : autoGenerated
      return base.map((p, i) => i === idx ? { ...p, text } : p)
    })
  }

  const handleAddCustom = () => {
    if (!customPrompt.trim()) return
    setCustomPrompts(prev => [...prev, { text: customPrompt.trim(), type: customType }])
    setCustomPrompt('')
  }

  const buildData = (runScan: boolean) => {
    const ownBrand: Brand = {
      id: brandName.trim().toLowerCase().replace(/\s+/g, '-'),
      name: brandName.trim(),
      color: brandColor,
      isOwn: true,
    }
    const compBrands: Brand[] = competitors.map(c => ({
      id: c.name.toLowerCase().replace(/\s+/g, '-'),
      name: c.name,
      color: c.color,
      isOwn: false,
    }))
    const now = new Date().toISOString().slice(0, 10)
    const finalPrompts: PromptDraft[] = [...effectiveGenerated, ...customPrompts]
    const prompts: Prompt[] = finalPrompts.map((p, i) => ({
      id: `onb-${i}`,
      text: p.text,
      type: p.type,
      tags: [ownBrand.id],
      createdAt: now,
    }))
    const attributes: Attribute[] = selectedAttrs.map((name, i) => ({
      id: name.toLowerCase().replace(/\s+/g, '-'),
      name,
      description: '',
      active: true,
      order: i,
      isIntended: true,
    }))
    onComplete({ ownBrand, competitors: compBrands, prompts, attributes, runScan })
  }

  const stepLabels = ['Your brand', 'Your competitors', 'Your attributes', 'Your first prompts']

  return (
    <div className="min-h-screen bg-background flex justify-center">
      <div className="w-full max-w-md px-6 pt-24 pb-12">
        {/* Compact stepper — constant size across steps */}
        {step < 4 && (
          <div className="mb-8">
            <div className="flex items-center gap-1.5 mb-2">
              {stepLabels.map((_, i) => (
                <div
                  key={i}
                  className={`h-1 flex-1 rounded-full transition-colors ${
                    i < step ? 'bg-primary' : i === step ? 'bg-primary/60' : 'bg-border'
                  }`}
                />
              ))}
            </div>
            <div className="flex items-center justify-between">
              <p className="text-xs font-medium text-foreground">{stepLabels[step]}</p>
              <p className="text-[10px] text-muted-foreground tabular-nums">
                Step {step + 1} of {stepLabels.length}
              </p>
            </div>
          </div>
        )}

        {/* Stable content area — prevents jumpy vertical shifts between steps */}
        <div className="min-h-[460px]">

        {/* Step 0 — Brand */}
        {step === 0 && (
          <div className="space-y-4">
            <div>
              <label className="block text-xs font-medium text-muted-foreground mb-1.5">Brand name</label>
              <input
                value={brandName}
                onChange={e => setBrandName(e.target.value)}
                placeholder="e.g. Acme Corp"
                className="w-full px-3 py-2 text-sm bg-background border border-border rounded-md text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-1 focus:ring-primary"
              />
            </div>
            <div>
              <label className="block text-xs font-medium text-muted-foreground mb-1.5">Brand colour</label>
              <div className="flex gap-1.5">
                {SWATCHES.map(c => (
                  <button
                    key={c}
                    onClick={() => setBrandColor(c)}
                    className={`w-7 h-7 rounded-full border-2 transition-colors ${
                      brandColor === c ? 'border-foreground scale-110' : 'border-transparent'
                    }`}
                    style={{ backgroundColor: c }}
                  />
                ))}
              </div>
            </div>
            <button
              disabled={!brandName.trim()}
              onClick={() => setStep(1)}
              className="w-full mt-2 px-4 py-2.5 text-sm font-medium bg-primary text-primary-foreground rounded-md hover:opacity-90 disabled:opacity-40 transition-opacity"
            >
              Next →
            </button>
          </div>
        )}

        {/* Step 1 — Competitors */}
        {step === 1 && (
          <div className="space-y-4">
            {competitors.length > 0 && (
              <div className="space-y-1.5">
                {competitors.map((c, i) => (
                  <div key={i} className="flex items-center gap-2 bg-card border border-border rounded-md px-3 py-2">
                    <span className="w-3 h-3 rounded-full" style={{ backgroundColor: c.color }} />
                    <span className="text-xs text-foreground flex-1">{c.name}</span>
                    <button
                      onClick={() => setCompetitors(prev => prev.filter((_, j) => j !== i))}
                      className="text-muted-foreground hover:text-destructive text-xs"
                    >
                      ×
                    </button>
                  </div>
                ))}
              </div>
            )}
            {competitors.length < 4 && (
              <div className="flex items-center gap-2">
                <input
                  value={compName}
                  onChange={e => setCompName(e.target.value)}
                  placeholder="Competitor name"
                  onKeyDown={e => e.key === 'Enter' && handleAddComp()}
                  className="flex-1 px-3 py-2 text-sm bg-background border border-border rounded-md text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-1 focus:ring-primary"
                />
                <button
                  onClick={() => setCompColor(SWATCHES[(SWATCHES.indexOf(compColor) + 1) % SWATCHES.length])}
                  className="w-7 h-7 rounded-full border-2 border-border shrink-0"
                  style={{ backgroundColor: compColor }}
                />
                <button
                  onClick={handleAddComp}
                  disabled={!compName.trim()}
                  className="px-3 py-2 text-sm bg-secondary text-secondary-foreground rounded-md hover:opacity-90 disabled:opacity-40"
                >
                  Add
                </button>
              </div>
            )}
            <div className="flex gap-2 pt-2">
              <button
                onClick={() => setStep(2)}
                className="flex-1 px-4 py-2.5 text-sm font-medium bg-primary text-primary-foreground rounded-md hover:opacity-90"
              >
                Next →
              </button>
              {competitors.length === 0 && (
                <button
                  onClick={() => setStep(2)}
                  className="px-4 py-2.5 text-sm text-muted-foreground hover:text-foreground"
                >
                  Skip
                </button>
              )}
            </div>
          </div>
        )}

        {/* Step 2 — Attributes */}
        {step === 2 && (
          <div className="space-y-4">
            <p className="text-xs text-muted-foreground leading-relaxed">
              What attributes do you want <span className="font-medium text-foreground">{brandName}</span> to be known for? Pick the associations you'd like LLMs to surface about your brand.
            </p>

            <div className="flex flex-wrap gap-1.5">
              {SUGGESTED_ATTRIBUTES.map(attr => {
                const active = selectedAttrs.includes(attr)
                return (
                  <button
                    key={attr}
                    onClick={() => toggleAttr(attr)}
                    className={`px-2.5 py-1 rounded-full text-[11px] font-medium transition-colors ${
                      active
                        ? 'bg-primary text-primary-foreground'
                        : 'bg-secondary text-secondary-foreground hover:bg-accent'
                    }`}
                  >
                    {attr}
                    {active && <span className="ml-1">×</span>}
                  </button>
                )
              })}
            </div>

            {/* Custom attributes already added (not in suggestions) */}
            {selectedAttrs.filter(a => !SUGGESTED_ATTRIBUTES.includes(a)).length > 0 && (
              <div className="flex flex-wrap gap-1.5">
                {selectedAttrs.filter(a => !SUGGESTED_ATTRIBUTES.includes(a)).map(attr => (
                  <button
                    key={attr}
                    onClick={() => toggleAttr(attr)}
                    className="px-2.5 py-1 rounded-full text-[11px] font-medium bg-primary text-primary-foreground transition-colors"
                  >
                    {attr} <span className="ml-1">×</span>
                  </button>
                ))}
              </div>
            )}

            <div className="flex gap-2">
              <input
                value={customAttr}
                onChange={e => setCustomAttr(e.target.value)}
                placeholder="Add your own attribute…"
                onKeyDown={e => e.key === 'Enter' && handleAddCustomAttr()}
                className="flex-1 px-3 py-2 text-sm bg-background border border-border rounded-md text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-1 focus:ring-primary"
              />
              <button
                onClick={handleAddCustomAttr}
                disabled={!customAttr.trim()}
                className="px-3 py-2 text-sm bg-secondary text-secondary-foreground rounded-md hover:opacity-90 disabled:opacity-40"
              >
                Add
              </button>
            </div>

            <div className="flex gap-2 pt-2">
              <button
                onClick={() => setStep(3)}
                className="flex-1 px-4 py-2.5 text-sm font-medium bg-primary text-primary-foreground rounded-md hover:opacity-90"
              >
                {selectedAttrs.length > 0 ? 'Next →' : 'Next →'}
              </button>
              {selectedAttrs.length === 0 && (
                <button
                  onClick={() => setStep(3)}
                  className="px-4 py-2.5 text-sm text-muted-foreground hover:text-foreground"
                >
                  Skip
                </button>
              )}
            </div>
          </div>
        )}

        {/* Step 3 — Prompts */}
        {step === 3 && (
          <div className="space-y-4">
            <p className="text-xs text-muted-foreground leading-relaxed">
              We ask LLMs different kinds of questions to surface what they associate with{' '}
              <span className="font-medium text-foreground">{brandLabel}</span>. Pick which types to track.
            </p>

            {/* Category + segment inputs */}
            <div className="grid grid-cols-2 gap-2">
              <div>
                <label className="block text-[10px] font-medium text-muted-foreground mb-1">Category</label>
                <input
                  value={category}
                  onChange={e => { setCategory(e.target.value); setEditingPrompts(false) }}
                  placeholder="e.g. CRM"
                  className="w-full px-2.5 py-1.5 text-xs bg-background border border-border rounded-md text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-1 focus:ring-primary"
                />
              </div>
              <div>
                <label className="block text-[10px] font-medium text-muted-foreground mb-1">Segment <span className="text-muted-foreground/60">(optional)</span></label>
                <input
                  value={segment}
                  onChange={e => { setSegment(e.target.value); setEditingPrompts(false) }}
                  placeholder="e.g. SMEs"
                  className="w-full px-2.5 py-1.5 text-xs bg-background border border-border rounded-md text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-1 focus:ring-primary"
                />
              </div>
            </div>

            {/* Type toggles, ordered by realism */}
            <div className="space-y-1.5">
              {(['category', 'competitor_anchored', 'association_probe'] as PromptType[]).map(t => {
                const meta = TYPE_META[t]
                const enabled = enabledTypes[t]
                return (
                  <button
                    key={t}
                    onClick={() => { setEnabledTypes(prev => ({ ...prev, [t]: !prev[t] })); setEditingPrompts(false) }}
                    className={`w-full text-left px-3 py-2.5 rounded-md border transition-colors ${
                      enabled
                        ? 'bg-primary/10 border-primary'
                        : 'bg-card border-border hover:border-primary/50'
                    }`}
                  >
                    <div className="flex items-center gap-2 mb-0.5">
                      <span className={`w-3.5 h-3.5 rounded-sm border flex items-center justify-center text-[9px] ${enabled ? 'bg-primary border-primary text-primary-foreground' : 'border-border'}`}>
                        {enabled ? '✓' : ''}
                      </span>
                      <span className="text-xs font-medium text-foreground">{meta.label}</span>
                      <span className="text-[9px] text-muted-foreground">#{meta.rank} most realistic</span>
                    </div>
                    <p className="text-[11px] text-muted-foreground ml-5.5 pl-0.5">{meta.blurb}</p>
                  </button>
                )
              })}
            </div>

            {/* Generated prompt preview, editable */}
            {effectiveGenerated.length > 0 && (
              <div className="space-y-1">
                <div className="flex items-center justify-between">
                  <span className="text-[10px] uppercase tracking-wide text-muted-foreground">We'll ask ({effectiveGenerated.length})</span>
                  {editingPrompts && (
                    <button
                      onClick={() => { setEditingPrompts(false); setGeneratedPrompts([]) }}
                      className="text-[10px] text-muted-foreground hover:text-foreground"
                    >
                      Reset to defaults
                    </button>
                  )}
                </div>
                {effectiveGenerated.map((p, i) => (
                  <div key={`${p.type}-${i}`} className="flex items-center gap-1.5 bg-card border border-border rounded-md px-2 py-1.5">
                    <span className="text-[9px] uppercase font-medium tracking-wide text-primary shrink-0 w-16">
                      {TYPE_META[p.type].label}
                    </span>
                    <input
                      value={p.text}
                      onChange={e => updateGenerated(i, e.target.value)}
                      className="flex-1 px-1.5 py-0.5 text-xs bg-transparent text-foreground focus:outline-none focus:bg-background rounded"
                    />
                    <button
                      onClick={() => removeGenerated(i)}
                      className="text-muted-foreground hover:text-destructive text-xs shrink-0"
                    >
                      ×
                    </button>
                  </div>
                ))}
              </div>
            )}

            {/* Advanced: custom prompts */}
            <div>
              <button
                onClick={() => setShowAdvanced(v => !v)}
                className="text-[10px] text-muted-foreground hover:text-foreground flex items-center gap-1"
              >
                <span>{showAdvanced ? '▾' : '▸'}</span>
                <span>Advanced — add custom prompts</span>
              </button>
              {showAdvanced && (
                <div className="mt-2 space-y-1.5">
                  <div className="flex gap-1">
                    {(['category', 'competitor_anchored', 'association_probe'] as PromptType[]).map(t => (
                      <button
                        key={t}
                        onClick={() => setCustomType(t)}
                        className={`px-2 py-0.5 rounded text-[10px] font-medium transition-colors ${
                          customType === t ? 'bg-primary text-primary-foreground' : 'bg-secondary text-secondary-foreground'
                        }`}
                      >
                        {TYPE_META[t].label}
                      </button>
                    ))}
                  </div>
                  <div className="flex gap-2">
                    <input
                      value={customPrompt}
                      onChange={e => setCustomPrompt(e.target.value)}
                      placeholder="Write your own prompt…"
                      onKeyDown={e => e.key === 'Enter' && handleAddCustom()}
                      className="flex-1 px-3 py-2 text-sm bg-background border border-border rounded-md text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-1 focus:ring-primary"
                    />
                    <button
                      onClick={handleAddCustom}
                      disabled={!customPrompt.trim()}
                      className="px-3 py-2 text-sm bg-secondary text-secondary-foreground rounded-md hover:opacity-90 disabled:opacity-40"
                    >
                      Add
                    </button>
                  </div>
                  {customPrompts.length > 0 && (
                    <div className="space-y-1">
                      {customPrompts.map((p, i) => (
                        <div key={`c-${i}`} className="flex items-center gap-1.5 bg-card border border-border rounded-md px-2 py-1.5">
                          <span className="text-[9px] uppercase font-medium tracking-wide text-primary shrink-0 w-16">
                            {TYPE_META[p.type].label}
                          </span>
                          <span className="text-xs text-foreground flex-1 truncate">{p.text}</span>
                          <button
                            onClick={() => setCustomPrompts(prev => prev.filter((_, j) => j !== i))}
                            className="text-muted-foreground hover:text-destructive text-xs shrink-0"
                          >
                            ×
                          </button>
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              )}
            </div>

            <button
              disabled={allPrompts.length < 1}
              onClick={() => setStep(4)}
              className="w-full px-4 py-2.5 text-sm font-medium bg-primary text-primary-foreground rounded-md hover:opacity-90 disabled:opacity-40 transition-opacity"
            >
              {allPrompts.length < 1 ? 'Enable at least one prompt type' : `Next → (${allPrompts.length} prompts)`}
            </button>
          </div>
        )}

        {/* Final screen */}
        {step === 4 && (
          <div className="text-center space-y-6">
            <div>
              <h2 className="text-lg font-semibold text-foreground mb-2">You're ready.</h2>
              <p className="text-sm text-muted-foreground">
                Run your first scan to see how LLMs perceive{' '}
                <span className="font-medium text-foreground">{brandName}</span>.
              </p>
            </div>

            <div>
              <label className="block text-xs text-muted-foreground mb-2">Select model</label>
              <div className="flex justify-center gap-1.5">
                {['ChatGPT', 'Claude', 'Gemini', 'All'].map(m => (
                  <button
                    key={m}
                    onClick={() => setSelectedModel(m)}
                    className={`px-3 py-1 rounded-md text-xs font-medium transition-colors ${
                      selectedModel === m ? 'bg-primary text-primary-foreground' : 'bg-secondary text-secondary-foreground'
                    }`}
                  >
                    {m}
                  </button>
                ))}
              </div>
            </div>

            <div className="space-y-2">
              <button
                onClick={() => buildData(true)}
                className="w-full px-6 py-3 text-sm font-semibold text-white rounded-lg hover:opacity-90 transition-opacity"
                style={{ backgroundColor: '#6C3EF4' }}
              >
                Run first scan ↗
              </button>
              <button
                onClick={() => buildData(false)}
                className="w-full px-6 py-2.5 text-sm text-muted-foreground hover:text-foreground transition-colors"
              >
                Skip — I'll scan later
              </button>
            </div>
          </div>
        )}
        </div>
      </div>
    </div>
  )
}
